kind: pipeline
name: export

platform:
  os: linux
  arch: amd64

steps:
- name: linux
  image: barichello/godot-ci:3.1.1
  commands:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - "godot -v --export \"Linux/X11\" ./build/linux/test.x86_64"

- name: windows
  image: barichello/godot-ci:3.1.1
  commands:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - "godot -v --export \"Windows Desktop\" ./build/windows/test.exe"

- name: mac
  image: barichello/godot-ci:3.1.1
  commands:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - "godot -v --export \"Mac OSX\" ./build/mac/test.zip"